# Generated by Django 4.0 on 2021-12-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin -  Can delete members'), ('regular', 'Regular - Can"t delete members')], max_length=10),
        ),
    ]
